services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
        APP_NAME: "Laravel"
        APP_ENV: "local"
        APP_KEY: "base64:yfFDeP8V5W+9TxQda1vhwPJd1Rs55u1+OVqw8nzx/Y8="
        APP_DEBUG: "true"
        APP_TIMEZONE: "UTC"
        APP_URL: "http://localhost"
        APP_LOCALE: "fr"
        APP_FALLBACK_LOCALE: "fr"
        APP_FAKER_LOCALE: "fr_FR"
        APP_MAINTENANCE_DRIVER: "file"
        APP_MAINTENANCE_STORE: "database"
        BCRYPT_ROUNDS: "12"
        LOG_CHANNEL: "stack"
        LOG_STACK: "single"
        LOG_DEPRECATIONS_CHANNEL: "null"
        LOG_LEVEL: "debug"
        SESSION_DRIVER: "database"
        SESSION_LIFETIME: "120"
        SESSION_ENCRYPT: "false"
        SESSION_PATH: "/"
        SESSION_DOMAIN: "null"
        BROADCAST_CONNECTION: "log"
        FILESYSTEM_DISK: "local"
        QUEUE_CONNECTION: "database"
        CACHE_STORE: "database"
        DB_CONNECTION: "mysql"
        DB_HOST: "mysql"
        DB_DATABASE: "laravel"
        DB_USERNAME: "laravel"
        DB_PASSWORD: "laravel"
    command: sh -c "if [ ! -d 'vendor' ]; then composer install; fi && php artisan serve --host=0.0.0.0 --port=8000"

  mysql:
    image: mysql:8.0-oracle
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
